apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  accessModes:
  - ReadWriteOnce   # Only one node can mount this
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0ccceed2df028a46b

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static-pv   # Volume name must be taken by Pv metadat name 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi