# PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  accessModes:
  - ReadWriteOnce   # Only one node can mount this
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0ccceed2df028a46b

---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static-pv   # Volume name must be taken by Pv metadat name 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

---
# Nginx pod
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:  # docker run -v host-path:container-path
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static-pvc

---
# service-loadbalancer
apiVersion: v1
kind: Service
metadata: 
  name: ebs-static-svc
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port


  # first create volume in aws
  # attach to EBSpolicy  one node
  # install drivers
  # create pv and pvc
  # create pod and one servie either loadbalancer
  # check in browser
  # delete volumes dont forget for practice purpose