apiVersion: v1
kind: Pod
metadate:
  name: resources
spec:
  containers:
     - name: nginx
       image: nginx
       resources:
         requests: # soft limit
            memory: "64Mi"
            cpu: "100m"
         limits: # hard limit
           memory: "128Mi"
           cpu: "150m"          